/**
 * Factory utilities for creating virtual printer instances and test data
 */

import { VirtualPrinterEngine, createDefaultConfig } from '../core/virtual-printer-engine';
import { CanonicalReceipt } from '../types/receipt';
import { randomBytes } from 'crypto';

/**
 * Create a virtual printer instance with sensible defaults
 */
export function createVirtualPrinter(
  merchantId: string,
  options: {
    secretKey?: string;
    forwardToPhysicalPrinter?: boolean;
    generateQRCode?: boolean;
    printerFilters?: string[];
  } = {}
): VirtualPrinterEngine {
  const secretKey = options.secretKey || generateSecretKey();
  const config = createDefaultConfig(merchantId, secretKey);

  // Apply options
  if (options.forwardToPhysicalPrinter !== undefined) {
    config.dualOutput.forwardToPhysicalPrinter = options.forwardToPhysicalPrinter;
  }

  if (options.generateQRCode !== undefined) {
    config.dualOutput.generateQRCode = options.generateQRCode;
  }

  if (options.printerFilters) {
    config.printCapture.printerFilters = options.printerFilters;
  }

  return new VirtualPrinterEngine(config);
}

/**
 * Generate a secure secret key
 */
export function generateSecretKey(): string {
  return randomBytes(32).toString('hex');
}

/**
 * Create a test receipt for development and testing
 */
export function createTestReceipt(merchantId: string, options: {
  merchantName?: string;
  items?: Array<{ name: string; qty: number; price: number }>;
  paymentMethod?: 'CASH' | 'MPESA' | 'CARD';
  includeKraPin?: boolean;
} = {}): CanonicalReceipt {
  const now = new Date().toISOString();
  const receiptId = `tbr_test_${Date.now()}_${Math.random().toString(36).substring(2, 8)}`;
  
  const defaultItems = [
    { name: 'Ugali', qty: 1, price: 150 },
    { name: 'Sukuma Wiki', qty: 1, price: 100 },
    { name: 'Nyama Choma', qty: 1, price: 350 }
  ];

  const items = (options.items || defaultItems).map(item => ({
    name: item.name,
    qty: item.qty,
    unit_price: item.price,
    total_price: item.qty * item.price,
    sku: undefined,
    tax_rate: undefined,
    tax_amount: undefined,
    discount: undefined,
    category: undefined
  }));

  const subtotal = items.reduce((sum, item) => sum + item.total_price, 0);
  const tax = Math.round(subtotal * 0.16 * 100) / 100; // 16% VAT
  const total = subtotal + tax;

  return {
    receipt_id: receiptId,
    merchant: {
      id: merchantId,
      name: options.merchantName || 'Test Restaurant',
      kra_pin: options.includeKraPin ? 'P051234567A' : undefined,
      location: '123 Test Street, Nairobi',
      address: '123 Test Street, Nairobi, Kenya',
      phone: '+254700123456',
      email: 'test@restaurant.com'
    },
    transaction: {
      receipt_no: `R${Date.now().toString().slice(-6)}`,
      datetime: now,
      currency: 'KES',
      payment_method: options.paymentMethod || 'CASH',
      pos_reference: `POS${Math.random().toString().slice(-4)}`,
      cashier: 'Test Cashier'
    },
    items,
    totals: {
      subtotal,
      tax,
      discount: 0,
      service_charge: 0,
      total
    },
    footer: {
      message: 'Thank you for dining with us!',
      terms: 'All sales are final',
      return_policy: 'No returns on food items',
      contact_info: 'Call +254700123456 for inquiries'
    },
    signature: '', // Will be generated by security manager
    etims_status: 'NOT_ENABLED',
    created_at: now,
    updated_at: now
  };
}

/**
 * Create test print data in various formats
 */
export function createTestPrintData(format: 'ESC_POS' | 'PLAIN_TEXT' | 'PDF' = 'PLAIN_TEXT'): Buffer {
  const receipt = createTestReceipt('test-merchant');
  
  switch (format) {
    case 'PLAIN_TEXT':
      return Buffer.from(formatReceiptAsPlainText(receipt), 'utf8');
    
    case 'ESC_POS':
      return createESCPOSData(receipt);
    
    case 'PDF':
      // In a real implementation, this would generate actual PDF data
      return Buffer.from('%PDF-1.4\n%Test PDF receipt data\n', 'utf8');
    
    default:
      return Buffer.from(formatReceiptAsPlainText(receipt), 'utf8');
  }
}

/**
 * Format receipt as plain text
 */
function formatReceiptAsPlainText(receipt: CanonicalReceipt): string {
  return `
${receipt.merchant.name}
${receipt.merchant.address || ''}
${receipt.merchant.phone || ''}

Receipt #: ${receipt.transaction.receipt_no}
Date: ${new Date(receipt.transaction.datetime).toLocaleDateString()}
Time: ${new Date(receipt.transaction.datetime).toLocaleTimeString()}
Cashier: ${receipt.transaction.cashier || 'N/A'}

Items:
${receipt.items.map((item: any) => 
  `${item.name.padEnd(20)} ${item.qty}x${item.unit_price.toFixed(2)} ${item.total_price.toFixed(2)}`
).join('\n')}

${'='.repeat(40)}
Subtotal:                ${receipt.totals.subtotal.toFixed(2)}
Tax (16%):               ${receipt.totals.tax.toFixed(2)}
${receipt.totals.discount > 0 ? `Discount:                ${receipt.totals.discount.toFixed(2)}\n` : ''}
Total:                   ${receipt.totals.total.toFixed(2)}

Payment: ${receipt.transaction.payment_method || 'CASH'}

${receipt.footer?.message || ''}
${receipt.footer?.contact_info || ''}

${'='.repeat(40)}
${receipt.merchant.kra_pin ? `KRA PIN: ${receipt.merchant.kra_pin}` : ''}
Powered by TABEZA Virtual Printer
  `.trim();
}

/**
 * Create ESC/POS formatted data
 */
function createESCPOSData(receipt: CanonicalReceipt): Buffer {
  const commands: number[] = [];
  
  // Initialize printer
  commands.push(0x1B, 0x40); // ESC @
  
  // Center alignment
  commands.push(0x1B, 0x61, 0x01); // ESC a 1
  
  // Bold on
  commands.push(0x1B, 0x45, 0x01); // ESC E 1
  
  // Merchant name
  const merchantName = receipt.merchant.name + '\n';
  commands.push(...Array.from(Buffer.from(merchantName, 'utf8')));
  
  // Bold off
  commands.push(0x1B, 0x45, 0x00); // ESC E 0
  
  // Left alignment
  commands.push(0x1B, 0x61, 0x00); // ESC a 0
  
  // Receipt content
  const content = formatReceiptAsPlainText(receipt);
  commands.push(...Array.from(Buffer.from(content, 'utf8')));
  
  // Feed and cut
  commands.push(0x1B, 0x64, 0x03); // ESC d 3 (feed 3 lines)
  commands.push(0x1D, 0x56, 0x00); // GS V 0 (cut)
  
  return Buffer.from(commands);
}

/**
 * Create a development/testing configuration
 */
export function createDevelopmentConfig(merchantId: string) {
  return {
    merchantId,
    printCapture: {
      platform: 'linux' as const,
      captureMethod: 'cups' as const,
      merchantId,
      printerFilters: ['test', 'dev', 'virtual']
    },
    dualOutput: {
      forwardToPhysicalPrinter: false, // Don't forward in development
      generateQRCode: true,
      qrCodeFormat: 'both' as const,
      deliveryMethods: ['qr_code' as const],
      physicalPrinterSettings: {
        preserveFormatting: true,
        addQRToReceipt: false,
        qrPosition: 'bottom' as const
      }
    },
    sync: {
      maxQueueSize: 100,
      retryIntervals: [5, 10, 30], // Shorter intervals for development
      batchSize: 5,
      connectionCheckInterval: 10,
      priorityWeights: {
        critical: 100,
        high: 75,
        medium: 50,
        low: 25
      }
    },
    security: {
      hashAlgorithm: 'sha256' as const,
      signatureAlgorithm: 'hmac-sha256' as const,
      secretKey: generateSecretKey(),
      enableTimestampValidation: false, // Relaxed for development
      maxReceiptAge: 86400,
      enableIntegrityChecks: true
    }
  };
}